CREATE TABLE met_instrument_types (
  id                       SERIAL PRIMARY KEY,
  label                    TEXT NOT NULL UNIQUE,
  category                 TEXT NOT NULL CHECK (category IN (
    'temperature_humidity', 'pressure', 'wind', 'radiation',
    'rain_gauge', 'soil', 'leaf_wetness', 'snow', 'weather_station', 'datalogger'
  )),
  manufacturer             TEXT NOT NULL,
  model                    TEXT NOT NULL,
  parameters               JSONB,
  requires_sensitivity     BOOLEAN NOT NULL DEFAULT false,
  requires_transfer_std    BOOLEAN NOT NULL DEFAULT false,
  transfer_std_parameters  TEXT[],
  maintenance_checks       JSONB NOT NULL DEFAULT '{}',
  active                   BOOLEAN NOT NULL DEFAULT true,
  notes                    TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX ON met_instrument_types (category);
CREATE INDEX ON met_instrument_types (active) WHERE active = true;

INSERT INTO met_instrument_types
  (label, category, manufacturer, model, parameters,
   requires_sensitivity, requires_transfer_std, transfer_std_parameters,
   maintenance_checks, active)
VALUES

('Campbell Scientific Hygrovue 5', 'temperature_humidity',
 'Campbell Scientific', 'Hygrovue 5',
 '{"temperature":{"range":"-40 to +70°C","accuracy":"±0.4°C","resolution":"0.001°C","tolerance":0.2},"humidity":{"range":"0-100%","accuracy":"±3%","resolution":"0.001%","tolerance":2}}'::jsonb,
 false, true, ARRAY['temperature','humidity'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":true,"desiccant_replaced":true,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific Hygrovue 10', 'temperature_humidity',
 'Campbell Scientific', 'Hygrovue 10',
 '{"temperature":{"range":"-40 to +70°C","accuracy":"±0.4°C","resolution":"0.001°C","tolerance":0.2},"humidity":{"range":"0-100%","accuracy":"±3%","resolution":"0.001%","tolerance":2}}'::jsonb,
 false, true, ARRAY['temperature','humidity'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":true,"desiccant_replaced":true,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific CS215', 'temperature_humidity',
 'Campbell Scientific', 'CS215',
 '{"temperature":{"range":"-40 to +70°C","accuracy":"±0.4°C","resolution":"0.01°C","tolerance":0.2},"humidity":{"range":"0-100%","accuracy":"±4%","resolution":null,"tolerance":2}}'::jsonb,
 false, true, ARRAY['temperature','humidity'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":true,"desiccant_replaced":true,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Rotronic HC2S3', 'temperature_humidity',
 'Rotronic', 'HC2S3',
 '{"temperature":{"range":"-40 to +60°C","accuracy":"±0.1°C","resolution":null,"tolerance":0.2},"humidity":{"range":"0-100%","accuracy":"±2.8%","resolution":null,"tolerance":2}}'::jsonb,
 false, true, ARRAY['temperature','humidity'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":true,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('E+E Elektronik EE181', 'temperature_humidity',
 'E+E Elektronik', 'EE181',
 '{"temperature":{"range":"-40 to +60°C","accuracy":"±0.2°C","resolution":null,"tolerance":0.2},"humidity":{"range":"0-100%","accuracy":"±2.3%","resolution":null,"tolerance":2}}'::jsonb,
 false, true, ARRAY['temperature','humidity'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":true,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Vaisala PTB110', 'pressure',
 'Vaisala', 'PTB110',
 '{"pressure":{"range":"500-1100 hPa","accuracy":"±1.0 hPa","resolution":"0.1 hPa","tolerance":0.5}}'::jsonb,
 false, true, ARRAY['pressure'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific Barovue', 'pressure',
 'Campbell Scientific', 'Barovue',
 '{"pressure":{"range":null,"accuracy":null,"resolution":null,"tolerance":0.5}}'::jsonb,
 false, true, ARRAY['pressure'],
 '{"level_as_found":true,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific Climavue 50 G2', 'weather_station',
 'Campbell Scientific', 'Climavue 50 G2',
 '{"temperature":{"range":null,"accuracy":null,"resolution":null,"tolerance":0.2},"humidity":{"range":null,"accuracy":null,"resolution":null,"tolerance":2},"pressure":{"range":null,"accuracy":null,"resolution":null,"tolerance":0.5}}'::jsonb,
 false, true, ARRAY['temperature','humidity','pressure'],
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":true,"orientation_verification":true,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Texas Electronics TR-525 6"', 'rain_gauge',
 'Texas Electronics', 'TR-525 with 6" funnel',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Texas Electronics TE-525 6"', 'rain_gauge',
 'Texas Electronics', 'TE-525 with 6" funnel',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Texas Electronics TR525-USW 8"', 'rain_gauge',
 'Texas Electronics', 'TR525-USW with 8" funnel',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Texas Electronics TR-525-I-01-CA 6"', 'rain_gauge',
 'Texas Electronics', 'TR-525-I-01-CA with 6" funnel',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Texas Electronics TR525-U-01-CA 8"', 'rain_gauge',
 'Texas Electronics', 'TR525-U-01-CA with 8" funnel',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('RM Young 03002', 'wind',
 'RM Young', '03002',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":true,"bearing_condition":true,"bearings_replaced":true}'::jsonb,
 true),

('Gill Instruments Windsonic WS75', 'wind',
 'Gill Instruments', 'Windsonic WS75 Black Opt1',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":true,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Kipp & Zonen CMP3', 'radiation',
 'Kipp & Zonen', 'CMP3',
 NULL,
 true, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Kipp & Zonen CUV5', 'radiation',
 'Kipp & Zonen', 'CUV5',
 NULL,
 true, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":true,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Kipp & Zonen NR Lite 2', 'radiation',
 'Kipp & Zonen', 'NR Lite 2',
 NULL,
 true, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Kipp & Zonen CNR4', 'radiation',
 'Kipp & Zonen', 'CNR4',
 NULL,
 true, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":true,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('LICOR LI-190', 'radiation',
 'LICOR', 'LI-190',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific CS616', 'soil',
 'Campbell Scientific', 'CS616',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific CS655', 'soil',
 'Campbell Scientific', 'CS655',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific T109', 'soil',
 'Campbell Scientific', 'T109',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific T108', 'soil',
 'Campbell Scientific', 'T108',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Campbell Scientific T107', 'soil',
 'Campbell Scientific', 'T107',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('Meter Group Phytos 31', 'leaf_wetness',
 'Meter Group', 'Phytos 31',
 NULL,
 false, false, NULL,
 '{"level_as_found":false,"level_if_adjusted":false,"live_reading":false,"sensor_element_replaced":true,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true),

('RM Young 52202', 'snow',
 'RM Young', '52202',
 NULL,
 false, false, NULL,
 '{"level_as_found":true,"level_if_adjusted":true,"live_reading":true,"sensor_element_replaced":false,"filter_replacement":false,"desiccant_replaced":false,"orientation_verification":false,"bearing_condition":false,"bearings_replaced":false}'::jsonb,
 true);
