ALTER TABLE column_name_mappings
  ADD COLUMN IF NOT EXISTS uz_units    TEXT,
  ADD COLUMN IF NOT EXISTS uz_measure  TEXT,
  ADD COLUMN IF NOT EXISTS node_arid    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS node_efteon  BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS node_fynbos  BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS node_gfw     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS node_ndlovu  BOOLEAN NOT NULL DEFAULT false;
